include "Day-1 Trebuchet/cpp"
include "Day-2 Cube Conundrum"
include "Day-3 Gear Ratios"
include "Day-5 If You Give A Seed A Fertilizer"
include "Day-7 Camel Cards"
include "Day-9 Mirage Maintenance"
include "Day-11 Cosmic Expansion"
include "Day-13 Point of Incidence"
include "Day-15 Lens Library"
include "Day-17 Clumsy Crucible"
--include "Day-19" 
--include "Day-21" 
--include "Day-23" 
