[package]
name = "PipeMaze"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pipe_maze_part_one"

[[bin]]
name = "pipe_maze_part_two"

[dependencies]
itertools = "0.12.0"
