[package]
name = "Scratchcards"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "scratchcards_part_one"

[[bin]]
name = "scratchcards_part_two"