[package]
name = "Hot_Springs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "hot_springs_part_one"

[[bin]]
name = "hot_springs_part_two"

[dependencies]
