[package]
name = "pulse_propagation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "pulse_propagation_part_one"

[[bin]]
name = "pulse_propagation_part_two"

[dependencies]
num = "0.4.1"
